### ISSUE TITLE
[golang] resource support

### ISSUE THREAD

**Issue by rvolosatovs** [wrpc/wrpc#41]

**Comment by ZhaoTzuHsien** [comment]
Does this project need any contributors?

**Comment by rvolosatovs** [comment]
> Does this project need any contributors?

Hi @ZhaoTzuHsien - yes, absolutely! This exact issue is already worked on and I'm planning to have a PR open for it today.

Are you interested in Go support specifically?

Also, I'll try to do a better job in filing issues for things that are open to be worked on

**Comment by ZhaoTzuHsien** [comment]
Yes, but I want to figure out the purpose and the architecture of the project first.

I find that the project is using Nats as the transport layer, is it somewhat similar to the architecture of WasmCloud?

**Comment by rvolosatovs** [comment]
> Yes, but I want to figure out the purpose and the architecture of the project first.
> 
> I find that the project is using Nats as the transport layer, is it somewhat similar to the architecture of WasmCloud?

NATS is just the first transport used by wRPC and a formal specification of wRPC-over-NATS is coming soon-ish

wRPC is indeed used by wasmCloud, but wRPC is not specific to wasmCloud, in fact, it has been decided to use wRPC fo plugin support in Wasmtime.

I was planning to get IPC #9 transport layer implemented as the first target, but I won't have capacity to work on it for the next 2-ish weeks. Another potentially very good transport candidate could be QUIC.

Would you be interested in working on a transport layer alternative to NATS? (IPC and QUIC are just suggestions, really anything you prefer)
